### ISSUE TITLE
상품 등록

### ISSUE THREAD

**Issue by ayoung-dev** [ayoung-dev/GridsCircles#5]
### 작업 상세 내용
- 상품의 기본 정보를 등록
ㄴ 상품명, 카테고리, 가격, 상품 상세정보

### TODO
- [x] ProductRepository - insert SQL 연결
- [x] ProductService - addProduct 함수 구현
- [x] ProductController - addProduct 함수 구현
