### ISSUE TITLE
상품 수정

### ISSUE THREAD

**Issue by ayoung-dev** [ayoung-dev/GridsCircles#7]
### 작업 상세 내용
- 상품 정보를 수정

### TODO
- [x] ProductRepository - update SQL 연결
- [x] ProductService - updateProduct 함수 구현
- [x] ProductController - updateProduct 함수 구현
